theme: jekyll-theme-minimal
logo: /assets/photo.png
title: [Dan Qiao]
description: [Master student of Automotive Engineering, Beihang University, China; interested in multi-agent reinforcement learning]
show_downloads: true
